# This file was automatically generated by pywxrc, do not edit by hand.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res


class xrcFRAME(wx.Frame):
    def PreCreate(self):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle()."""
        pass

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        get_resources().LoadOnFrame(pre, parent, "FRAME")
        self.PreCreate()
        self.PostCreate(pre)

        # Define variables for the controls
        self.SPanel = xrc.XRCCTRL(self, "SPanel")



# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    cbscroll_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxFrame" name="FRAME">
    <title/>
    <object class="wxScrolledWindow" name="SPanel">
      <object class="wxBoxSizer">
        <orient>wxVERTICAL</orient>
        <object class="sizeritem">
          <object class="wxButton">
            <label>a big label just for some fun</label>
          </object>
          <flag>wxALL|wxALIGN_CENTRE</flag>
          <border>10</border>
        </object>
        <object class="sizeritem">
          <object class="wxStaticBoxSizer">
            <label>Box Label</label>
            <orient>wxVERTICAL</orient>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>one</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>two</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>three</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>four</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>five</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>six</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>seven</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>eight</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>nine</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>ten</label>
              </object>
            </object>
          </object>
          <flag>wxALL|wxEXPAND</flag>
          <border>10</border>
        </object>
        <object class="sizeritem">
          <object class="wxStaticLine"/>
          <flag>wxEXPAND</flag>
        </object>
        <object class="sizeritem">
          <object class="wxStaticBoxSizer">
            <label>Another Label</label>
            <orient>wxVERTICAL</orient>
            <object class="sizeritem">
              <object class="wxFlexGridSizer">
                <cols>3</cols>
                <rows>2</rows>
                <object class="sizeritem">
                  <object class="wxStaticText">
                    <label>other controls too:</label>
                  </object>
                  <flag>wxALL|wxALIGN_CENTRE|wxALIGN_CENTRE_VERTICAL</flag>
                  <border>10</border>
                </object>
                <object class="sizeritem">
                  <object class="wxTextCtrl"/>
                </object>
                <object class="sizeritem">
                  <object class="wxButton">
                    <label>button</label>
                  </object>
                </object>
                <object class="sizeritem">
                  <object class="wxStaticText">
                    <label>another:</label>
                  </object>
                  <flag>wxALIGN_RIGHT|wxALIGN_CENTRE_VERTICAL</flag>
                </object>
                <object class="sizeritem">
                  <object class="wxTextCtrl"/>
                </object>
                <vgap>3</vgap>
                <hgap>4</hgap>
                <object class="sizeritem">
                  <object class="wxButton">
                    <label>button</label>
                  </object>
                </object>
              </object>
            </object>
          </object>
          <flag>wxALL|wxEXPAND</flag>
          <border>10</border>
        </object>
        <object class="sizeritem">
          <object class="wxStaticLine"/>
          <flag>wxEXPAND</flag>
        </object>
        <object class="sizeritem">
          <object class="wxStaticBoxSizer">
            <label>One more label</label>
            <orient>wxVERTICAL</orient>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>eleven</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>twelve</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>thirteen</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>fourteen</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>fifteen</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>sixteen</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>seventeen</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>eighteen</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>ninteen</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxCheckBox">
                <label>twenty</label>
              </object>
            </object>
          </object>
          <flag>wxALL|wxEXPAND</flag>
          <border>10</border>
        </object>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/cbscroll/cbscroll_xrc', cbscroll_xrc)
    __res.Load('memory:XRC/cbscroll/cbscroll_xrc')


 	  	 
