// -*- C++ -*- generated by wxGlade 0.5 on Sun Jan 29 16:05:50 2012

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef TEST_BUG_H
#define TEST_BUG_H


class CDialog: public wxDialog {
public:
    // begin wxGlade: CDialog::ids
    // end wxGlade

    CDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);
	void OnRadio1Clicked(wxCommandEvent &event);
	void OnRadio2Clicked(wxCommandEvent &event);
private:
    // begin wxGlade: CDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: CDialog::attributes
    wxRadioButton* radio_btn_1;
    wxTextCtrl* text_ctrl_1;
    wxRadioButton* radio_btn_2;
    wxButton* button_1;
    wxButton* button_2;
    wxPanel* panel_1;
    // end wxGlade
}; // wxGlade: end class


#endif // TEST_BUG_H
