#!/usr/bin/env python
# generated by wxGlade 0.3.1 on Sat Dec 27 08:49:38 2003

from wxPython.wx import *

class MainFrame(wxFrame):
    
    ID_BTN_OPENDLG = wxNewId()
    
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wxDEFAULT_FRAME_STYLE
        wxFrame.__init__(self, *args, **kwds)
        self.btnGo = wxButton(self, self.ID_BTN_OPENDLG, "Open Dlg")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("Main Frame")
        # end wxGlade
        EVT_BUTTON(self, self.ID_BTN_OPENDLG, self.onOpenDlgClick)

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wxBoxSizer(wxVERTICAL)
        sizer_1.Add(self.btnGo, 0, wxALL, 4)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

    def onOpenDlgClick(self, e):
        dlg = Dialog(self, -1, '')
        try:
            dlg.ShowModal()
        finally:
            dlg.Destroy()

# end of class MainFrame


class Dialog(wxDialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Dialog.__init__
        kwds["style"] = wxDEFAULT_DIALOG_STYLE
        wxDialog.__init__(self, *args, **kwds)
        self.btnClose = wxButton(self, wxID_CANCEL, "Close")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Dialog.__set_properties
        self.SetTitle("Dialog")
        self.btnClose.SetDefault()
        # end wxGlade
        EVT_CLOSE(self, self.onCloseWindow)

    def __do_layout(self):
        # begin wxGlade: Dialog.__do_layout
        sizer_2 = wxBoxSizer(wxVERTICAL)
        sizer_2.Add(self.btnClose, 0, wxALL, 4)
        self.SetAutoLayout(1)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        sizer_2.SetSizeHints(self)
        self.Layout()
        # end wxGlade

    def onCloseWindow(self, e):
        print 'Closing window'
        self.Close()

# end of class Dialog


class MyApp(wxApp):
    def OnInit(self):
        wxInitAllImageHandlers()
        frmMain = MainFrame(None, -1, "")
        self.SetTopWindow(frmMain)
        frmMain.Show(1)
        return 1

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()

 	  	 
