// -*- C++ -*- generated by wxGlade 0.5 on Mon Jun 18 17:22:29 2007 from Z:\WIP\RadioBox Bug Test\Test.wxg

#include <wx/wx.h>
// begin wxGlade: ::dependencies
// end wxGlade


class MyFrame: public wxFrame
{
public:
    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE)
    : wxFrame(parent, id, title, pos, size, wxCAPTION|wxCLOSE_BOX|wxMINIMIZE_BOX|wxSYSTEM_MENU|wxTAB_TRAVERSAL|wxCLIP_CHILDREN)
	{
		const wxString radio_box_1_choices[] = {
			wxT("choice 1"),
			wxT("choice 2"),
			wxT("choice 3"),
			wxT("choice 4"),
			wxT("choice 5")
		};
		radio_box_1 = new wxRadioBox(this, wxID_ANY, wxT("Test"), wxDefaultPosition, wxDefaultSize, 5, radio_box_1_choices, 1, wxRA_SPECIFY_ROWS);
		
	    SetTitle(wxT("frame_1"));
		SetBackgroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_BTNFACE));
		radio_box_1->SetSelection(0);

		wxBoxSizer* rootSizer = new wxBoxSizer(wxVERTICAL);
		rootSizer->Add(radio_box_1, 0, 0, 0);
		SetSizer(rootSizer);
		rootSizer->Fit(this);
		Layout();
		Centre();

	}

    void OnRadioBox(wxCommandEvent &event)  { wxMessageBox(wxString::Format(wxT("EVT_RADIOBOX index = %d"), event.GetInt())); }

    wxRadioBox* radio_box_1;

    DECLARE_EVENT_TABLE();
};

BEGIN_EVENT_TABLE(MyFrame, wxFrame)
    EVT_RADIOBOX(wxID_ANY, MyFrame::OnRadioBox)
END_EVENT_TABLE();

class MyApp: public wxApp
{
public:
    bool OnInit()
    {
    MyFrame* frame_1 = new MyFrame(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(frame_1);
    frame_1->Show();
    return true;
	}

};

IMPLEMENT_APP(MyApp)
 	  	 
