// -*- C++ -*- generated by wxGlade 0.4.1 on Sun Apr 22 15:04:12 2007

#include "test.h"
#include "sample.xpm"

BEGIN_EVENT_TABLE(MyDialog,wxDialog)
	EVT_PAINT(MyDialog::OnPaint)
END_EVENT_TABLE()

MyDialog::MyDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: MyDialog::MyDialog
    sizer_4_staticbox = new wxStaticBox(this, -1, wxT("Select a Bitmap"));
    bmp1 = new wxStaticBitmap(this, -1, wxBitmap(sample_xpm));
    bmp2 = new wxStaticBitmap(this, -1, wxBitmap(sample_xpm));
    label_2 = new wxStaticText(this, -1, wxT("bitmap 1"));
    label_3 = new wxStaticText(this, -1, wxT("bitmap 2"));
    label_1 = new wxStaticText(this, -1, wxT("Selected bitmap:"));
    m_OK = new wxButton(this, wxID_OK, wxT("OK"));
    m_Cancel = new wxButton(this, wxID_CANCEL, wxT("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade
}


void MyDialog::set_properties()
{
    // begin wxGlade: MyDialog::set_properties
    SetTitle(wxT("Test Dialog"));
    m_OK->SetDefault();
    // end wxGlade
}


void MyDialog::do_layout()
{
    // begin wxGlade: MyDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    wxStaticBoxSizer* sizer_4 = new wxStaticBoxSizer(sizer_4_staticbox, wxHORIZONTAL);
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(2, 2, 5, 5);
    sizer_1->Add(5, 20, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
    sizer_2->Add(20, 5, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
    grid_sizer_1->Add(bmp1, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
    grid_sizer_1->Add(bmp2, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
    grid_sizer_1->Add(label_2, 0, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
    grid_sizer_1->Add(label_3, 0, wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
    sizer_4->Add(grid_sizer_1, 0, wxEXPAND|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 0);
    sizer_3->Add(sizer_4, 0, wxEXPAND, 0);
    sizer_3->Add(20, 5, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
    sizer_3->Add(label_1, 0, wxADJUST_MINSIZE, 0);
    sizer_2->Add(sizer_3, 0, wxEXPAND, 0);
    sizer_2->Add(20, 5, 0, wxADJUST_MINSIZE, 0);
    sizer_5->Add(m_OK, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
    sizer_5->Add(5, 20, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
    sizer_5->Add(m_Cancel, 0, wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL|wxADJUST_MINSIZE, 0);
    sizer_2->Add(sizer_5, 0, wxEXPAND, 0);
    sizer_2->Add(20, 5, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
    sizer_1->Add(sizer_2, 0, wxEXPAND, 0);
    sizer_1->Add(5, 20, 0, wxEXPAND|wxADJUST_MINSIZE, 0);
    SetAutoLayout(true);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    sizer_1->SetSizeHints(this);
    Layout();
    Centre();
    // end wxGlade
	bmp1->SetFocus();
}

void MyDialog::OnPaint(wxPaintEvent &WXUNUSED(event))
{
	wxPaintDC dc( this );
	wxClientDC dc1( sizer_4_staticbox );
	dc1.SetBackgroundMode( wxTRANSPARENT );
	dc1.SetPen( *wxBLACK_PEN );
	wxPoint pos;
	wxSize size;
	pos = bmp1->GetPosition();
	size = bmp1->GetSize();
	dc1.DrawRectangle( pos.x - 2, pos.y - 2, size.x + 6, size.y + 6 );
}


 	  	 
