// -*- C++ -*- generated by wxGlade 0.4.1 on Sun Apr 22 15:04:12 2007

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef TEST_H
#define TEST_H


class MyDialog: public wxDialog {
public:
    // begin wxGlade: MyDialog::ids
    // end wxGlade

    MyDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

	void OnPaint(wxPaintEvent &event);
	DECLARE_EVENT_TABLE()

private:
    // begin wxGlade: MyDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyDialog::attributes
    wxStaticBox* sizer_4_staticbox;
    wxStaticBitmap* bmp1;
    wxStaticBitmap* bmp2;
    wxStaticText* label_2;
    wxStaticText* label_3;
    wxStaticText* label_1;
    wxButton* m_OK;
    wxButton* m_Cancel;
    // end wxGlade
}; // wxGlade: end class


#endif // TEST_H

 	  	 
