#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4cvs on Wed May 18 08:50:52 2005

import wx
import wx.grid

class FrmGridTester(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FrmGridTester.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.choice = wx.Choice(self, -1, choices=["This", "is", "a", "good", "and", "valid", "test"])
        self.grid = wx.grid.Grid(self, -1, size=(1, 1))
        self.btnQuit = wx.Button(self, -1, "Quit")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_CHOICE, self.onChoice_CHOICE, self.choice)
        self.Bind(wx.grid.EVT_GRID_CMD_SELECT_CELL, self.onGrid_SELECT_CELL, self.grid)
        self.Bind(wx.EVT_BUTTON, self.onBtnQuit_BUTTON, self.btnQuit)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FrmGridTester.__set_properties
        self.SetTitle("Grid Tester")
        self.SetMinSize((640, 480))
        self.choice.SetSelection(0)
        self.grid.CreateGrid(100, 3)
        self.grid.SetRowLabelSize(20)
        self.grid.SetColLabelSize(20)
        self.grid.EnableEditing(0)
        self.grid.SetSelectionMode(wx.grid.Grid.wxGridSelectRows)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FrmGridTester.__do_layout
        sizer_main = wx.FlexGridSizer(2, 1, 0, 0)
        sizer_main.Add(self.choice, 0, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        sizer_main.Add(self.grid, 1, wx.EXPAND, 0)
        sizer_main.Add(self.btnQuit, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ADJUST_MINSIZE, 8)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_main)
        sizer_main.AddGrowableRow(1)
        sizer_main.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

    def onBtnQuit_BUTTON(self, event): # wxGlade: FrmGridTester.<event_handler>
        self.Destroy()

    def onGrid_SELECT_CELL(self, event): # wxGlade: FrmGridTester.<event_handler>
        print "CELL row=%d" % event.GetRow()
        # xxx if you dont use this... the choice will be keept the focus! xxx
        #self.grid.SetFocus()
        self.grid.SelectRow(event.GetRow())
        event.Skip()

    def onChoice_CHOICE(self, event): # wxGlade: FrmGridTester.<event_handler>
        print "CHOICE"
        event.Skip()

# end of class FrmGridTester


class AppGrid(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_1 = FrmGridTester(None, -1, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return 1

# end of class AppGrid

if __name__ == "__main__":
    appGrid = AppGrid(0)
    appGrid.MainLoop()

 	  	 
