#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade HG on Wed Jul  7 11:35:46 2010 from "/home/bvn/my/python/cpuxa/pxa_server.wxg"

import wx

# begin wxGlade: extracode
# end wxGlade



class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.dmx_statusbar = self.CreateStatusBar(3, wx.ST_SIZEGRIP)
        
        # Tool Bar
        self.frame_1_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.frame_1_toolbar)
        self.frame_1_toolbar.AddLabelTool(1, "stop", wx.Bitmap("./icons/Button-stop-32.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "stop polling", "")
        self.frame_1_toolbar.AddLabelTool(2, "kick", wx.Bitmap("./icons/Button-reboot-32.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "kick start polling", "")
        self.frame_1_toolbar.AddLabelTool(3, "start", wx.Bitmap("./icons/Button-go-32.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "start polling", "")
        self.frame_1_toolbar.AddLabelTool(4, "find", wx.Bitmap("./icons/Button-search-32.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "find configuration", "")
        self.frame_1_toolbar.AddLabelTool(5, "exit", wx.Bitmap("./icons/Button-shutdown-32.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "exit DMX server", "")
        # Tool Bar end
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("BvN's pxa/IP Ocelot server")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("./icons/dmax_server.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((500, 600))
        self.dmx_statusbar.SetStatusWidths([100, 150, 150])
        # statusbar fields
        dmx_statusbar_fields = ["poll_count", "ocelot_status", "inet_status"]
        for i in range(len(dmx_statusbar_fields)):
            self.dmx_statusbar.SetStatusText(dmx_statusbar_fields[i], i)
        self.frame_1_toolbar.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.text_ctrl_1, 1, wx.ALL|wx.EXPAND, 2)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class MyFrame


class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame1.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Tool Bar
        self.frame_2_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.frame_2_toolbar)
        self.frame_2_toolbar.AddLabelTool(10, "save", wx.Bitmap("./icons/Save-32.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "save configuration", "")
        self.frame_2_toolbar.AddLabelTool(11, "bail", wx.Bitmap("./icons/Close-32.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "do not change configuration", "")
        self.frame_2_toolbar.AddSeparator()
        self.frame_2_toolbar.AddLabelTool(12, "home", wx.Bitmap("./icons/Home-32.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "home directory", "")
        self.frame_2_toolbar.AddLabelTool(13, "up", wx.Bitmap("./icons/Top-32.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "parent directory", "")
        # Tool Bar end
        self.label_curr_config = wx.StaticText(self, -1, "label_1")
        self.label_curr_folder = wx.StaticText(self, -1, "label_1")
        self.choice_folder = wx.Choice(self, -1, choices=[])
        self.sizer_3_staticbox = wx.StaticBox(self, -1, "Folder")
        self.label_curr_file = wx.StaticText(self, -1, "label_1")
        self.choice_file = wx.Choice(self, -1, choices=[])
        self.sizer_5_staticbox = wx.StaticBox(self, -1, "FIle")
        self.label_curr_port = wx.StaticText(self, -1, "label_1")
        self.choice_port = wx.Choice(self, -1, choices=[])
        self.sizer_6_staticbox = wx.StaticBox(self, -1, "Port")
        self.label_curr_servicenum = wx.StaticText(self, -1, "lInet service number")
        self.spin_button_service = wx.SpinButton(self, -1 )
        self.sizer_7_staticbox = wx.StaticBox(self, -1, "Inet Service Number")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame1.__set_properties
        self.SetTitle("Server configuration")
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("./icons/Button-search-32.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((879, 220))
        self.frame_2_toolbar.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame1.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_7_staticbox.Lower()
        sizer_7 = wx.StaticBoxSizer(self.sizer_7_staticbox, wx.VERTICAL)
        self.sizer_6_staticbox.Lower()
        sizer_6 = wx.StaticBoxSizer(self.sizer_6_staticbox, wx.VERTICAL)
        self.sizer_5_staticbox.Lower()
        sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.VERTICAL)
        self.sizer_3_staticbox.Lower()
        sizer_3 = wx.StaticBoxSizer(self.sizer_3_staticbox, wx.VERTICAL)
        sizer_2.Add(self.label_curr_config, 0, wx.ALL|wx.EXPAND, 2)
        sizer_3.Add(self.label_curr_folder, 0, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 2)
        sizer_3.Add(self.choice_folder, 0, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 2)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_5.Add(self.label_curr_file, 0, wx.ALL|wx.EXPAND, 2)
        sizer_5.Add(self.choice_file, 0, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 2)
        sizer_4.Add(sizer_5, 1, wx.EXPAND, 0)
        sizer_6.Add(self.label_curr_port, 0, wx.ALL|wx.EXPAND, 2)
        sizer_6.Add(self.choice_port, 0, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 2)
        sizer_4.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_7.Add(self.label_curr_servicenum, 0, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 2)
        sizer_7.Add(self.spin_button_service, 0, wx.ALL|wx.EXPAND|wx.ADJUST_MINSIZE, 2)
        sizer_4.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

# end of class MyFrame1


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
